language: python
python:
  - 2.6
before_install:
  - sudo apt-get install libpcre3-dev
  - make download-cache
install:
  - make var/plonesite
  - make bin/pybot
  - make bin/supervisord
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: 
  - make test
  - make robot

