language: python
python:
  - 2.6
before_install:
  - make buildout-cache
install:
  - make bin/instance
  - make bin/pybot
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: 
  - make test
  - make robot

