language: python
python:
  - 2.6
before_install:
  - sudo apt-get install libpcre3-dev
install:
  - pip install coveralls
  - pip install --upgrade setuptools=0.9.8
  - pip install distribute
  - make bin/test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: 
  - make coverage
after_success:
  - coveralls
